name: flask-scaffold

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Cache pip
      uses: actions/cache@v2
      with:
       # This path is specific to Ubuntu
       path: ~/.cache/pip
       # Look to see if there is a cache hit for the corresponding requirements file
       key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
       restore-keys: |
         ${{ runner.os }}-pip-
         ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics --exclude venv --ignore E501,E722,F401
    - name: Test with pytest
      run: |
        pytest --suppress-no-test-exit-code